# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Develop Branch CI/CD

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  CI-CD:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./musix-frontend

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build --if-present
    
    - name: Run tests
      run: npm test -- --coverage
      
    - name: Lighthouse
      uses: foo-software/lighthouse-check-action@master
      with:
        urls: 'https://musix-fontys.github.io/MusiX-FrontEnd/home,https://musix-fontys.github.io/MusiX-FrontEnd/signup,https://musix-fontys.github.io/MusiX-FrontEnd/signin,https://musix-fontys.github.io/MusiX-FrontEnd/profile/77f9c419-e9f0-4d48-8d1e-5d0cbee36801,https://musix-fontys.github.io/MusiX-FrontEnd/artist/6l3HvQ5sa6mXTsMTB19rO5,https://musix-fontys.github.io/MusiX-FrontEnd/album/7viNUmZZ8ztn2UB4XB3jIL,https://musix-fontys.github.io/MusiX-FrontEnd/track/3XzSOIE6zGLliuqsVGLmUc,https://musix-fontys.github.io/MusiX-FrontEnd/search/test,https://musix-fontys.github.io/MusiX-FrontEnd/authorized'

    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
